const SKETCH_PROMPTS = [
  "Draw what's immediately in front of you.",
  "Draw how you feel right now using only shapes.",
  "Draw a deeply personal childhood memory.",
  "Draw your favorite coffee mug.",
  "Draw the view out of your closest window.",
  "Draw your own hands without looking at the paper.",
  "Draw a very fancy chair.",
  "Draw a creature that lives in a teacup.",
  "Draw what you think silence looks like.",
  "Draw an instrument you don't know how to play.",
  "Draw a houseplant that has taken over the room.",
  "Draw your favorite outfit.",
  "Draw a self-portrait, but as an animal.",
  "Draw a tree that grows something other than fruit.",
  "Draw an abstract representation of your morning routine.",
  "Draw a scene from your favorite book.",
  "Draw a pair of old, worn-out shoes.",
  "Draw an imaginary friend.",
  "Draw a busy city street in the rain.",
  "Draw a peaceful cabin in the woods.",
  "Draw what you eat for breakfast.",
  "Draw a strange insect.",
  "Draw a collection of keys.",
  "Draw a bouquet of unusual flowers.",
  "Draw something that makes you laugh.",
  "Draw a very intricate lock.",
  "Draw a map of an imaginary continent.",
  "Draw the feeling of falling.",
  "Draw something you lost a long time ago.",
  "Draw your dream studio space.",
  "Draw a close-up of an eye.",
  "Draw a bicycle leaning against a wall.",
  "Draw a boat on calm water.",
  "Draw a stormy sky.",
  "Draw a collection of vintage bottles.",
  "Draw your favorite dessert.",
  "Draw a dog catching a frisbee.",
  "Draw a cat asleep in a sunbeam.",
  "Draw a person reading on a bench.",
  "Draw a crowded bookshelf.",
  "Draw exactly what is on your desk right now.",
  "Draw a very tall stack of pancakes.",
  "Draw a glowing lantern in the dark.",
  "Draw a paper airplane.",
  "Draw a compass rose.",
  "Draw a mysterious door.",
  "Draw a staircase leading nowhere.",
  "Draw a bridge over a river.",
  "Draw a pair of glasses.",
  "Draw a wristwatch.",
  "Draw an old-fashioned telephone.",
  "Draw a modern cityscape.",
  "Draw a futuristic vehicle.",
  "Draw a robot doing a chore.",
  "Draw an alien landscape.",
  "Draw a castle on a cloud.",
  "Draw a secret cave entrance.",
  "Draw a treasure chest.",
  "Draw a magic wand.",
  "Draw a swirling galaxy.",
  "Draw the moon and stars.",
  "Draw a blazing campfire.",
  "Draw a melting candle.",
  "Draw a hot air balloon.",
  "Draw a collection of shells.",
  "Draw a woven basket.",
  "Draw a messy pile of clothes.",
  "Draw a neatly folded sweater.",
  "Draw a complex knot.",
  "Draw a spool of thread.",
  "Draw a pair of scissors.",
  "Draw a sewing machine.",
  "Draw an old typewriter.",
  "Draw a record player.",
  "Draw a grand piano.",
  "Draw a violin.",
  "Draw a trumpet.",
  "Draw a drum set.",
  "Draw a collection of tools.",
  "Draw a hammer and nails.",
  "Draw a wrench and screws.",
  "Draw a paint palette.",
  "Draw a bouquet of brushes.",
  "Draw a camera.",
  "Draw a telescope.",
  "Draw a microscope.",
  "Draw a magnifying glass.",
  "Draw a globe.",
  "Draw an opened letter.",
  "Draw a stack of envelopes.",
  "Draw a feather quill.",
  "Draw a fountain pen.",
  "Draw a notebook with messy handwriting.",
  "Draw a slice of pizza.",
  "Draw a bowl of soup.",
  "Draw a tangled mess of wires.",
  "Draw a perfect sphere.",
  "Draw a cracked mirror.",
  "Draw a spiderweb.",
  "Draw a delicate snowflake.",
  "Draw a chunk of ice.",
  "Draw a burning match.",
  "Draw a pocket watch.",
  "Draw an hourglass.",
  "Draw an hourglass running out of sand.",
  "Draw a grandfather clock.",
  "Draw a sundial.",
  "Draw a calendar.",
  "Draw a ringing bell.",
  "Draw a wind chime.",
  "Draw a whistle.",
  "Draw a boomerang.",
  "Draw a yo-yo.",
  "Draw a kite in the sky.",
  "Draw a spinning top.",
  "Draw a kaleidoscope.",
  "Draw a kaleidoscope pattern.",
  "Draw a puzzle piece.",
  "Draw a Rubik's cube.",
  "Draw a chessboard.",
  "Draw a pair of dice.",
  "Draw a deck of cards.",
  "Draw a domino.",
  "Draw a shiny marble.",
  "Draw a glowing crystal.",
  "Draw a diamond ring.",
  "Draw a pearl necklace.",
  "Draw a crown.",
  "Draw a tiara.",
  "Draw a king's scepter.",
  "Draw a knight's shield.",
  "Draw a sword and armor.",
  "Draw a bow and arrow.",
  "Draw a pirate ship.",
  "Draw a sunken anchor.",
  "Draw a steering wheel of a ship.",
  "Draw a lighthouse beacon.",
  "Draw a seagull in flight.",
  "Draw a pelican stealing food.",
  "Draw a crab on the beach.",
  "Draw a starfish.",
  "Draw a seahorse.",
  "Draw a jellyfish.",
  "Draw an octopus.",
  "Draw a swimming turtle.",
  "Draw a dolphin.",
  "Draw a shark leaping.",
  "Draw a majestic whale.",
  "Draw a stingray.",
  "Draw an eel.",
  "Draw a coral reef.",
  "Draw an underwater cavern.",
  "Draw a bubbling geyser.",
  "Draw a rushing waterfall.",
  "Draw a slow moving stream.",
  "Draw a babbling brook.",
  "Draw a frozen pond.",
  "Draw a snowman.",
  "Draw an igloo.",
  "Draw a pair of ice skates.",
  "Draw a sled.",
  "Draw a snowboard.",
  "Draw a pair of skis.",
  "Draw a skateboard.",
  "Draw a surfboard.",
  "Draw a rollerblade.",
  "Draw a scooter.",
  "Draw a unicycle.",
  "Draw a tricycle.",
  "Draw a tandem bicycle.",
  "Draw a moped.",
  "Draw a motorcycle.",
  "Draw a vintage car.",
  "Draw a sports car.",
  "Draw a monster truck.",
  "Draw a semi truck.",
  "Draw a train engine.",
  "Draw a caboose.",
  "Draw a subway car.",
  "Draw an airplane in the clouds.",
  "Draw a helicopter.",
  "Draw a drone.",
  "Draw a rocket ship.",
  "Draw a space shuttle.",
  "Draw a satellite.",
  "Draw the international space station.",
  "Draw an astronaut.",
  "Draw a space rover.",
  "Draw a lunar lander.",
  "Draw a Martian crater.",
  "Draw a Saturn rover.",
  "Draw a distant planet.",
  "Draw a shooting star.",
  "Draw a meteor.",
  "Draw an asteroid belt.",
  "Draw a comet.",
  "Draw the Milky Way.",
  "Draw a black hole.",
  "Draw a supernova.",
  "Draw a nebula.",
  "Draw a constellation you made up.",
  "Draw the Big Dipper.",
  "Draw the North Star.",
  "Draw a crescent moon.",
  "Draw a full moon.",
  "Draw an eclipse.",
  "Draw a solar flare.",
  "Draw a sunspot.",
  "Draw a cloud taking the shape of an animal.",
  "Draw a lightning bolt.",
  "Draw a tornado.",
  "Draw a hurricane.",
  "Draw a blizzard.",
  "Draw a dust storm.",
  "Draw a desert oasis.",
  "Draw a wild horse running.",
  "Draw a sleeping fox.",
  "Draw a soaring eagle.",
  "Draw a very colorful parrot.",
  "Draw an intricate clockwork mechanism.",
  "Draw a bowl of fresh fruit.",
  "Draw a glass half full of water.",
  "Draw a burning piece of toast.",
  "Draw an exploding star.",
  "Draw a field of wildflowers.",
  "Draw your favorite memory from last summer.",
  "Draw the texture of tree bark.",
  "Draw shadows cast by a window at noon.",
  "Draw a forgotten toy.",
  "Draw an old map with a trail leading nowhere.",
  "Draw a glowing potion bottle.",
  "Draw a broken sword.",
  "Draw a magical staff.",
  "Draw a cozy reading nook.",
  "Draw a stack of old vinyl records.",
  "Draw a classic arcade game machine.",
  "Draw a very elaborate birthday cake.",
  "Draw the scariest monster you can think of.",
  "Draw a peaceful koi pond.",
  "Draw a bustling farmer's market.",
  "Draw a delicate lace pattern.",
  "Draw something that is soft and plush.",
  "Draw an intense feeling of joy.",
  "Draw a memory of feeling lost.",
  "Draw what freedom looks like.",
  "Draw an endless hallway.",
  "Draw a spiral staircase.",
  "Draw a very sharp dagger.",
  "Draw a floating island.",
  "Draw a tiny garden in a bottle.",
  "Draw a pair of boots left by the door.",
  "Draw a plate of spaghetti.",
  "Draw the view from a moving train.",
  "Draw a stormy ocean.",
  "Draw a lighthouse in fog.",
  "Draw a streetlamp flicking on at dusk.",
  "Draw a very old, twisted tree.",
  "Draw a collection of mushrooms.",
  "Draw a sleeping dragon.",
  "Draw a friendly ghost.",
  "Draw the last thing you held in your hand."
];
